routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| ----- Definimos las rutas que va a tener nuestra aplicación -------------
|
| ** Para que las rutas funcionen hemos de activar el módulo rewrite de apache, 
| y cambiar la directiva AllowOverride de apache2.conf **
|
|
*/
 

/** 
 * Inicio ------------------
 */
Route::get('/', "CursoController@index"); // cargar oferta de cursos al inicio

Route::get('/busquedas', "CursoController@busqueda"); 
Route::get('/cursos/json', "CursoController@data");

Route::get('/cursos', "CursoController@catalogo");
Route::post('/contacto', "EmailsController@postContact");

Route::get('/curso/{slug}', "CursoController@show")->name('detalle-curso'); // ver detalle del curso

Route::get('/cursos/elearning/{fileName}', function() {
	dd('hola');
})->where(['fileName' => '.*']);


/** 
 * Autenticación usuario------------
 */
Route::group(['middleware' => 'prevent-back-history'],function(){

	Auth::routes();
	Route::get('/home', 'CursoController@index')->name('home');
	Route::get('users/confirmation/{token}', 'Auth\RegisterController@confirmation')->name('confirmation'); // Verificación Email
	Route::get('/login/{driver}', 'Auth\LoginController@redirectToProvider')->name('social_auth');
	Route::get('/login/{driver}/callback', 'Auth\LoginController@handleProviderCallback');


	/** Usuario ----------- */
	Route::middleware('auth')->group(function() {
		Route::get('/misdatos/editar',  'UserController@edit')->name('verperfil');
		Route::post('/user/editar-perfil',  'UserController@update')->name('editarperfil');
		Route::post('user/editar-cuenta', 'UserController@updatePassword')->name('changepassword');
		Route::delete('/user/baja',  'UserController@destroy')->name('baja');

		/** Panel de alumno ----------- */
		Route::get('/miscursos', "AlumnoController@index")->name('miscursos');
		Route::post('/add_valoracion', 'CursoController@addRating');
		Route::get('/curso/{slug}/learning', "AlumnoController@show")->name('cursar');
		Route::get('/curso/learning/show/{id}', 'AlumnoController@showFile')->name('curso.recurso.showfile');

	});


});

/** 
 * Cesta ---------------------
 */
Route::post('/cesta', 'DetalleCestaController@store'); // add item
Route::get('/cesta', 'CestaController@index')->name('cesta'); //show cesta
Route::delete('/cesta', 'DetalleCestaController@destroy'); // delete item
Route::get('/cesta/trash', 'CestaController@trash')->name('cesta-trash'); //vaciar cesta
Route::get('/cesta/checkout', 'CestaController@checkout') ->middleware('prevent-back-history','auth'); //inicio de pago
Route::post('/cesta/pago', 'CestaController@payment'); // confirmación pago


/** 
 * Panel de Administración ---
 */

Route::middleware(['prevent-back-history', 'auth', 'admin'])->prefix('admin')->namespace('Admin')->group(function () {

    Route::get('/', "CursoController@index")->name('admin'); //index admin
	Route::get('/usuarios', 'CursoController@viewInscritos')->name('usuarios');
	Route::get('/inscritos', 'CursoController@getUsers')->name('inscritos');
	Route::get('/compras', 'CursoController@getCursosComprados')->name('compras');

	// Cursos
    Route::group(['prefix' => 'cursos'], function() {

	    Route::get('/', "CursoController@getAllCursos")->name('cursos'); //listado
	    Route::get('/crear', "CursoController@create")->name('cursos.crear'); // formulario crear
	    Route::get('/{curso}', "CursoController@show")->name('curso'); //listado
		Route::post('/', "CursoController@store")->name('cursos.store'); // registrar form crear
		Route::get('/{slug}/editar', "CursoController@edit")->name('cursos.editar'); // formulario editar
		Route::put('/{curso}', "CursoController@update")->name('cursos.update'); // registrar 
		Route::delete('/{id}', "CursoController@destroy"); // delete
		Route::put('/{slug}/publicar', "CursoController@publicar")->name('cursos.publicar'); // publicar

		// Temas
		Route::resource('/temas', 'TemaController')->except([
		    'index', 'create', 'show', 'edit'
		]);
		Route::post('/temas/update-posicion', 'TemaController@updatePosicion')->name('temas.posicion');

		// Recursos
		Route::get('/temas/recursos/show', 'RecursoController@getAllRecursos')->name('recursos.getRecursos');
		Route::get('/temas/recursos/{id}', 'RecursoController@getRecurso');
		Route::post('/temas/recursos', 'RecursoController@store')->name('recursos.store');
		Route::put('/temas/recursos/{id}', 'RecursoController@update')->name('recursos.update');
		Route::delete('/temas/recursos/destroy', 'RecursoController@destroy')->name('recursos.destroy');
		Route::get('/temas/recurso/{id}', 'RecursoController@getFile')->name('recursos.display');


	});



});



/** DE PRUEBA --------------------- */
Route::get('admin/cursos/hola', function() {

	  //echo phpinfo();

});

resources/views/admin/partials/modal/add_recurso.blade.php
<!-- Modal para crear Recurso -->
<div class="modal fade" id="addMedia" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog">
    <!-- modal content -->
    <div class="modal-content">

      <!-- modal header -->
      <div class="modal-header">
        <h5 class="modal-title" >{{ __('Inserte un recurso') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- modal body / form  -->
        <form id="addRecursoForm" action="javascript:;" enctype="multipart/form-data" method="POST" accept-charset="UTF-8">
        {{ csrf_field() }}

        <div class="modal-body text-lef">Titulo
        <input type="hidden" id="tema_id" name="tema_id" value="">
          <div class="form-group">
              <input type="text" name="title" class="form-control" placeholder="Titulo del fichero a mostrar" />
                <small class="form-text invalid-feedback errorTitle"></small>
          </div>
          <div class="form-group">
            <div class="control-label">Fichero</div>
            <div class="custom-file mt-2">
            <input 
              type="file" 
              class="custom-file-input" 
              id="myfile"
              name="myfile" 
              lang="es" />
            <label class="custom-file-label" for="myfile">{{ __('Selecciona fichero') }}</label>
                <small class="form-text invalid-feedback errorFile"></small>
            </div>
          </div>      

        </div>
      <!-- modal body / form  -->
        <div class="modal-footer">
        <button type="submit" class="btn btn-danger">{{ __('Subir') }}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cerrar') }}</button>
        </div>
      </form>
    </div>
  </div>
</div>

@push('scripts')

  @if(count($errors->add_recurso)>0)
  <script>
  $(document).ready(function(){ 
      $('#addMedia').modal({show: true});
  });
  </script>
  @endif

  <script type="text/javascript">
  $(document).ready(function(){
      
      //Modal Submit vía Ajax
      $("#addRecursoForm").on('submit', function(e){
            //disable the default form submission
            e.preventDefault();
            var data = new FormData($(this)[0]);
            //var url = form.attr("action");
            $.ajax({
                type: "POST",
                dataType: "html",
                url: "{{ route('recursos.store') }}",
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                success: function(response){
                    var data = JSON.parse(response);
                    if(data.errors) {
                        if(data.errors.title) {
                          $("input[name='title']").addClass('is-invalid');
                          $(".errorTitle").text(data.errors.title);
                        }

                        if(data.errors.myfile) {
                          $("input[name='myfile']").addClass('is-invalid');
                          $(".errorFile").text(data.errors.myfile);
                        }
                        
                    } else {
                       showRecursos(response);
                       $("#addMedia").modal('hide');
                    }
                },
                error: function(){
                    alert("Ha habido un error. Vuelva a intentarlo.");
                }
            });
            //$("#addMedia").modal('hide');
      });
      
  });

  </script>
@endpush

resources/views/admin/partials/modal/add_tema.blade.php
<!-- Modal para crear Tema -->
<div class="modal fade" id="addTema" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog">
    <!-- modal content -->
    <div class="modal-content">

      <!-- modal header -->
      <div class="modal-header">
        <h5 class="modal-title" >{{ __('Añade un tema') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <!-- modal body / form  -->
      <form method="POST" action="{{ route('temas.store') }}">
        {{ csrf_field() }}

        <input type="hidden" name="curso_id" value="{{ $curso_ -> id }}">
        <div class="modal-body text-left">
          <div class="form-group d-block mt-2">
            <label class="control-label" for="title">{{ __('Titulo') }}</label>
            <input type="text" class="form-control{{ $errors->add_tema->has('title') ? ' is-invalid' : ''}}" id="title" placeholder="Titulo del tema" name="title" value="{{ old('title') }}" />
            @if($errors->add_tema->has('title'))
                <small class="form-text invalid-feedback">{{ $errors->add_tema->first('title') }}</small>
            @endif
          </div>
          <div class="form-group mt-2">
            <textarea class="form-control{{ $errors->add_tema->has('descripcion') ? ' is-invalid' : ''}}" id="descripcion" rows="3" placeholder="{{ __('Breve descripcion sobre el tema (*)') }}" aria-describedby="descripcionHelp" name="descripcion"></textarea>
            <small id="descripcionHelp" class="form-text text-muted">{{ _('* Opcional.') }}</small>
            @if($errors->add_tema->has('descripcion'))
                <small class="form-text invalid-feedback">{{ $errors->add_tema->first('descripcion') }}</small>
            @endif
          </div>
        </div>
      <!-- modal body / form  -->
        <div class="modal-footer">
        <button type="submit" class="btn btn-danger">{{ __('Añadir') }}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cerrar') }}</button>
        </div>
      </form>
    </div>
  </div>
</div>

@push('scripts')

  @if(count($errors->add_tema)>0)
  <script>
  $(document).ready(function(){ 
      $('#addTema').modal({show: true});
  });
  </script>
  @endif

@endpush

resources/views/admin/partials/modal/edit_recurso.blade.php
<!-- Modal para crear Recurso -->
<div class="modal fade" id="editMedia" tabindex="-1" role="dialog" aria-labelledby="editMediaModal" aria-hidden="true">
  <div class="modal-dialog">
    <!-- modal content -->
    <div class="modal-content">

      <!-- modal header -->
      <div class="modal-header">
        <h5 class="modal-title" id="editMediaModal">{{ __('Editar Recurso') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- modal body / form  -->
        <form id="editRecursoForm" action="javascript:;" enctype="multipart/form-data" method="POST" accept-charset="UTF-8">
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        <div class="modal-body text-lef">Titulo
        <input type="hidden" id="recurso_id" name="recurso_id" value="">
          <div class="form-group">
              <input type="text" name="title" class="form-control" value="" />
              <small class="form-text invalid-feedback errorTitle"></small>
          </div>
          <div class="form-group">
            <div class="control-label">Fichero</div>
            <div class="custom-file mt-2">
            <input 
              type="file" 
              class="custom-file-input" 
              id="myfile"
              name="myfile" 
              value=""
              lang="es" 
              autoComplete="off" />
            <label class="custom-file-label" for="myfile"><small></small></label>
                <small class="form-text invalid-feedback errorFile"></small>
            </div>
          </div>      

        </div>
      <!-- modal body / form  -->
        <div class="modal-footer">
        <button type="submit" class="btn btn-danger">{{ __('Subir') }}</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cerrar') }}</button>
        </div>
      </form>
    </div>
  </div>
</div>


@push('scripts')

  <script type="text/javascript">
  $(document).ready(function(){
      
      //Modal Submit vía Ajax
      $("#editRecursoForm").on('submit', function(e){
            //disable the default form submission
            e.preventDefault();
            var id = $("input[name='recurso_id']").val();
            var data = new FormData($(this)[0]);
            //var url = form.attr("action");
            $.ajax({
                type: "POST",
                dataType: "html",
                url: "{{ route('recursos.update', 'id') }}",
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                success: function(response){
                    var data = JSON.parse(response);
                    if(data.errors) {
                        if(data.errors.title) {
                          $("input[name='title']").addClass('is-invalid');
                          $(".errorTitle").text(data.errors.title);
                        }

                        if(data.errors.myfile) {
                          $("input[name='myfile']").addClass('is-invalid');
                          $(".errorFile").text(data.errors.myfile);
                        }
                        
                    } else {
                       showRecursos(response);
                       $("#editMedia").modal('hide');
                    }
                },
                error: function(){
                    alert("Ha habido un error. Vuelva a intentarlo.");
                    $("#editMedia").modal('hide');
                }
            });

      });
      
  });

  </script>
@endpush

resources/views/admin/partials/modal/edit_tema.blade.php
<!-- Modal para crear Tema -->

<div class="modal fade" id="editTema" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog">
    <!-- modal content -->
    <div class="modal-content">

      <!-- modal header -->
      <div class="modal-header">
        <h5 class="modal-title" >{{ __('Editar un tema') }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <!-- modal body / form  -->
      <form method="POST" action="{{ route('temas.update', 'tema') }}">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
          <div class="modal-body text-left">

            <input type="hidden" name="tema_id" id="tema_id" value="{{ $tema->id }}">

            <div class="form-group d-block mt-2">
              <label class="control-label" for="title">{{ __('Titulo') }}</label>
              <input type="text" class="form-control{{ $errors->edit_tema->has('title') ? ' is-invalid' : ''}}" id="title" name="title" value="{{ old('title') }}" />
              @if($errors->edit_tema->has('title'))
                  <small class="form-text invalid-feedback">{{ $errors->edit_tema->first('title') }}</small>
              @endif
            </div>

            <div class="form-group mt-2">
              <textarea class="form-control{{ $errors->edit_tema->has('descripcion') ? ' is-invalid' : ''}}" id="descripcion" rows="3" aria-describedby="descripcionHelp" name="descripcion"></textarea>
              <small id="descripcionHelp" class="form-text text-muted">{{ _('* Opcional.') }}</small>
              @if($errors->edit_tema->has('descripcion'))
                  <small class="form-text invalid-feedback">{{ $errors->edit_tema->first('descripcion') }}</small>
              @endif
            </div>
          </div>
        <!-- modal body / form  -->
          <div class="modal-footer">
              <button type="submit" class="btn btn-danger">{{ __('Guardar') }}
              </button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">{{ __('Cerrar') }}</button>
          </div>
      </form>
    </div>
  </div>
</div>

@push('scripts')

  @if(count($errors->edit_tema)>0)
  <script>
      $(document).ready(function(){ 
          $('#editTema').modal({show: true});
      });
  </script>
  @endif

@endpush

resources/views/admin/partials/modal/publicar_curso.blade.php
<!-- Modal de aviso para publicar un curso -->
<div class="modal fade" id="publicarModal" tabindex="-1" role="dialog" aria-labelledby="publicarCurso" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="publicarCurso"><i class="fa fa-exclamation-circle" aria-hidden="true"></i>&nbsp;&nbsp;Advertencia</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center m-3">
        Antes de proceder a visualizar el curso en la plataforma elearning, asegurese de que tiene todo el temario y sus recursos, listos para su visualización.
        <h6  class="mt-3 py-3 text-white bg-info">¿Está seguro de publicar su curso?</h6>
      </div>
      <div class="modal-footer">
        <form method="POST" action="{{ route('cursos.publicar', $curso->slug) }}">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <button type="submit" class="btn btn-warning">Publicar</button>
        </form>
      </div>
    </div>
  </div>
</div>