routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| ----- Definimos las rutas que va a tener nuestra aplicación -------------
|
| ** Para que las rutas funcionen hemos de activar el módulo rewrite de apache, 
| y cambiar la directiva AllowOverride de apache2.conf **
|
|
*/
 

/** 
 * Inicio ------------------
 */
Route::get('/', "CursoController@index"); // cargar oferta de cursos al inicio

Route::get('/busquedas', "CursoController@busqueda"); 
Route::get('/cursos/json', "CursoController@data");

Route::get('/cursos', "CursoController@catalogo");
Route::post('/contacto', "EmailsController@postContact");

Route::get('/curso/{slug}', "CursoController@show")->name('detalle-curso'); // ver detalle del curso

Route::get('/cursos/elearning/{fileName}', function() {
	dd('hola');
})->where(['fileName' => '.*']);


/** 
 * Autenticación usuario------------
 */
Route::group(['middleware' => 'prevent-back-history'],function(){

	Auth::routes();
	Route::get('/home', 'CursoController@index')->name('home');
	Route::get('users/confirmation/{token}', 'Auth\RegisterController@confirmation')->name('confirmation'); // Verificación Email
	Route::get('/login/{driver}', 'Auth\LoginController@redirectToProvider')->name('social_auth');
	Route::get('/login/{driver}/callback', 'Auth\LoginController@handleProviderCallback');


	/** Usuario ----------- */
	Route::middleware('auth')->group(function() {
		Route::get('/misdatos/editar',  'UserController@edit')->name('verperfil');
		Route::post('/user/editar-perfil',  'UserController@update')->name('editarperfil');
		Route::post('user/editar-cuenta', 'UserController@updatePassword')->name('changepassword');
		Route::delete('/user/baja',  'UserController@destroy')->name('baja');

		/** Panel de alumno ----------- */
		Route::get('/miscursos', "AlumnoController@index")->name('miscursos');
		Route::post('/add_valoracion', 'CursoController@addRating');
		Route::get('/curso/{slug}/learning', "AlumnoController@show")->name('cursar');
		Route::get('/curso/learning/show/{id}', 'AlumnoController@showFile')->name('curso.recurso.showfile');

	});


});

/** 
 * Cesta ---------------------
 */
Route::post('/cesta', 'DetalleCestaController@store'); // add item
Route::get('/cesta', 'CestaController@index')->name('cesta'); //show cesta
Route::delete('/cesta', 'DetalleCestaController@destroy'); // delete item
Route::get('/cesta/trash', 'CestaController@trash')->name('cesta-trash'); //vaciar cesta
Route::get('/cesta/checkout', 'CestaController@checkout') ->middleware('prevent-back-history','auth'); //inicio de pago
Route::post('/cesta/pago', 'CestaController@payment'); // confirmación pago


/** 
 * Panel de Administración ---
 */

Route::middleware(['prevent-back-history', 'auth', 'admin'])->prefix('admin')->namespace('Admin')->group(function () {

    Route::get('/', "CursoController@index")->name('admin'); //index admin
	Route::get('/usuarios', 'CursoController@viewInscritos')->name('usuarios');
	Route::get('/inscritos', 'CursoController@getUsers')->name('inscritos');
	Route::get('/compras', 'CursoController@getCursosComprados')->name('compras');

	// Cursos
    Route::group(['prefix' => 'cursos'], function() {

	    Route::get('/', "CursoController@getAllCursos")->name('cursos'); //listado
	    Route::get('/crear', "CursoController@create")->name('cursos.crear'); // formulario crear
	    Route::get('/{curso}', "CursoController@show")->name('curso'); //listado
		Route::post('/', "CursoController@store")->name('cursos.store'); // registrar form crear
		Route::get('/{slug}/editar', "CursoController@edit")->name('cursos.editar'); // formulario editar
		Route::put('/{curso}', "CursoController@update")->name('cursos.update'); // registrar 
		Route::delete('/{id}', "CursoController@destroy"); // delete
		Route::put('/{slug}/publicar', "CursoController@publicar")->name('cursos.publicar'); // publicar

		// Temas
		Route::resource('/temas', 'TemaController')->except([
		    'index', 'create', 'show', 'edit'
		]);
		Route::post('/temas/update-posicion', 'TemaController@updatePosicion')->name('temas.posicion');

		// Recursos
		Route::get('/temas/recursos/show', 'RecursoController@getAllRecursos')->name('recursos.getRecursos');
		Route::get('/temas/recursos/{id}', 'RecursoController@getRecurso');
		Route::post('/temas/recursos', 'RecursoController@store')->name('recursos.store');
		Route::put('/temas/recursos/{id}', 'RecursoController@update')->name('recursos.update');
		Route::delete('/temas/recursos/destroy', 'RecursoController@destroy')->name('recursos.destroy');
		Route::get('/temas/recurso/{id}', 'RecursoController@getFile')->name('recursos.display');


	});



});



/** DE PRUEBA --------------------- */
Route::get('admin/cursos/hola', function() {

	  //echo phpinfo();

});

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Curso;
use App\User;
use App\Rating;

class CursoController extends Controller
{
    

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        $cursos = Curso::with('categoria', 'ratings')
            ->where('estado', Curso::PUBLICADO)->get();
        
        //Generamos una vista a la que pasamos el objeto Curso
        return view('index', compact('cursos'));
    }



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        // Devuelve una colección vacía en caso de no encontrar registro
        $curso = Curso::with(
            [
                'categoria' => function($query) {
                    $query->select('id', 'nombre');
                }, 
                'objetivos' => function($query) {
                    $query->select('id', 'curso_id', 'objetivo');
                }, 
                'temas' => function($query) {
                    $query->select('id', 'curso_id', 'posicion', 'titulo', 'descripcion')->orderBy('posicion');
                }, 
                'ratings.user'
            ]
        )->withCount(['users', 'ratings'])
         ->where('slug', $slug)
         ->first();
        
        $from = false; //no inscrito
        $relacionados = $curso->cursosRelacionados();
        return view('curso', compact('curso', 'relacionados', 'from'));
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function catalogo()
    { 
        $cursos = Curso::withCount(['users'])
            ->with('categoria', 'ratings')
            ->where('estado', Curso::PUBLICADO)
            ->get();
        //dd($cursos);
        //Generamos una vista a la que pasamos el objeto Curso
        return view('catalogo', compact('cursos'));
    }


    public function busqueda(Request $request)
    { 
        $query = $request->consulta;
        $cursos = Curso::Busqueda($query)
            ->paginate(6);

        //Si solo hay un curso de busqueda que me envíe a él directamente
        if ($cursos -> count() == 1) {
            $slug= $cursos->first()->slug;
            return redirect('curso/' . $slug);
        }

        //Enviamos el objeto Curso a la vista
        return view('busquedas', compact('cursos', 'query'));
    }


    //Metodo que devuelve un array con todos los titulos del curso
    public function data()
    { 
        $cursos = Curso::pluck('titulo');
        return $cursos;
    }

    // Método que añade una valoración a un curso
    public function addRating () {
        $rating = new Rating();
        $rating->user_id = auth()->user()->id;
        $rating->curso_id = request('curso_id');
        $rating->valoracion = request('rating_input');
        $rating->comentario = request('msj_valoracion');
        $rating->save();

        return back()->with('mensaje', 'Muchas gracias por valorar el curso');

    }


}

resources/views/admin/partials/curso_card.blade.php
<a href="{{url('/admin/cursos/'. $curso -> slug)}}"
   style="color: inherit; text-decoration:none;">
      <div class="card mb-4">
          <div class="card-body p-0">
            <div class="row">
            <div class="col-md-6">
                    <img src="{{ url('/storage/' . $curso -> imagen) }}" 
                    alt="{{ $curso->titulo }}" height="100%" class="card-img-top mr-3">
            </div>
            <div class="col-md-6 pl-0">
                <div class="info-top">
                    <h5 class="mt-2 d-block text-truncate" style="max-width: 375px;">{{ $curso->titulo }}</h5>
                    <h6 class="mt-2 d-block text-truncate" style="max-width: 375px;">{{ $curso->titulo2 }}</h6>
                    <span class="p-1 badge-secondary">{{ $curso->categoria->nombre }}</span><br>
                    <small>{{ __('Estudiantes') }}: {{ $curso->users_count }}</small>
                  </div>
                  <div class="info-bottom d-flex pt-4">
                      <div class="info-center-left">
                        <div>{{ $curso->created_at->format('d/m/Y') }}</div>
                        @include('partials.cursos.rating')
                      </div>
                      <div class="info-center-right ml-auto p-4">
                            <span><i class="fa fa-clock-o" aria-hidden="true"></i>&nbsp;&nbsp;{{ number_format($curso->duracion, 0) }} h
                            </span>
                            <span class="ml-1">| {{ number_format($curso->precio, 0) }} €</i>
                            </span>
                      </div>
                  </div>
            </div>
                        
          </div> 
          <div class="card-footer text-right">
              <div class="btn-group" role="group" aria-label="Basic example">
                  <a href="{{ url('/admin/cursos/'. $curso -> slug .'/editar') }}" class="btn btn-outline-success btn-xs mr-1"><i class="fa fa-edit"></i>&nbsp;&nbsp;Editar</a>
                  <form method="post" action="{{ url('/admin/cursos/'. $curso -> id) }}">{{ csrf_field()}}
                    {{ method_field('DELETE')}}
                    <button type="submit" rel="tooltip" title="Eliminar curso" class="btn btn-outline-danger btn-xs mr-1"><i class="fa fa-times"></i>&nbsp;&nbsp;Eliminar</button>
                  </form>
                  @if(($curso->estado == \App\Curso::PENDIENTE))
                    <button class="btn btn-outline-warning" class="btn btn-primary" data-toggle="modal" data-target="#publicarModal"><i class="fa fa-history" aria-hidden="true"></i>&nbsp;&nbsp;Publicar</button>
                    @include('admin.partials.modal.publicar_curso')
                  @endif
                </div>
          </div>
          </div>
      </div>
</a>  

resources/views/admin/partials/curso_form.blade.php
<!-- Formulario de Curso -->


<form 
method="POST" 
action="{{ ! $curso_->id ? route('cursos.store') : route('cursos.update', $curso_->slug) }}" 
novalidate
enctype="multipart/form-data">
	{{ csrf_field() }}
	@if($method == 'PUT')
		{{ method_field('PUT') }}
	@endif

		<!-- titulo principal -->
		<div class="col-sm-12">
			<div class="form-group label-floating">
				<label for="titulo" class="control-label h5">Titulo principal</label>
				<input type="text" class="form-control form-control-lg{{ $errors->curso_form->has('titulo') ? ' is-invalid' : ''}}" name="titulo" value="{{ old('titulo') ?: $curso_->titulo}}"></input>
				@include('admin.partials.errors.form_alert', ['field' => 'titulo'])
			</div>
		</div>

		<!-- titulo secundario -->
		<div class="col-sm-12">
			<div class="form-group label-floating">
				<label for="titulo2" class="control-label">Titulo secundario <small>(opcional)</small></label>
				<input type="text" 
						class="form-control{{ $errors->curso_form->has('titulo2') ? ' is-invalid' : ''}}" 
						name="titulo2" 
						value="{{ old('titulo2') ?: $curso_->titulo2 }}"
						required
				></input>
				@include('admin.partials.errors.form_alert', ['field' => 'titulo2'])
			</div>
		</div>
		
		<!-- categoría-->
		<div class="col-sm-12">
			<div class="form-group label-floating">
				<label for="categoria_id" class="control-label">Categoría</label>
				<select class="form-control" name="categoria_id">
					@foreach(\App\Categoria::pluck('nombre', 'id') as $id => $nombre)
						<option {{ (int) old('categoria_id') === $id || $curso_->categoria_id === $id ? 'selected' : ''}} value="{{ $id }}">
							{{ $nombre }}
						</option>
					@endforeach
				</select>
			</div>
		</div>
			
		<!-- duración, precio y descuento -->
		<div class="col-sm-12 px-0 d-inline-flex">
			<div class="col-sm-4 form-group label-floating">
				<label class="control-label">Duración</label>
				<input type="number" class="form-control{{ $errors->curso_form->has('duracion') ? ' is-invalid' : ''}}" name="duracion" value="{{ old('duracion') ?: $curso_->duracion }}"></input>
				@include('admin.partials.errors.form_alert', ['field' => 'duracion'])
			</div>

			<div class="col-sm-4 form-group">
				<label class="control-label">Precio</label>
				<input type="number" class="form-control{{ $errors->curso_form->has('precio') ? ' is-invalid' : ''}}" name="precio" value="{{ old('precio') ?: $curso_->precio }}"></input>
				@include('admin.partials.errors.form_alert', ['field' => 'precio'])
			</div>

			<div class="col-sm-4 form-group">
				<label class="control-label">Descuento (%)</label>
				<input type="number" class="form-control{{ $errors->curso_form->has('descuento') ? ' is-invalid' : ''}}" name="descuento" value="{{ old('descuento') ?: $curso_->descuento }}"></input>
				@include('admin.partials.errors.form_alert', ['field' => 'descuento'])
			</div>		
		</div>
		<!-- imagen -->
		<div class="col-sm-12">
			<div class="form-group">
				<div class="control-label">Imagen</div>
				<div class="custom-file mt-2">
					<input 
						type="file" 
						class="custom-file-input{{ $errors->curso_form->has('image') ? ' is-invalid' : ''}}" 
						id="image"
						name="image" 
						lang="es" />
					<label class="custom-file-label" for="image"><small>
						{{ ! $curso_->id ? __('Selecciona portada curso') : $curso_->imagen }}
					</small></label>
					@include('admin.partials.errors.form_alert', ['field' => 'image'])

				</div>
			</div>			
		</div>

		<!--dirigido a -->
		<div class="col-sm-12">
			<div class="form-group">
				<label for="dirigido_a" class="control-label">Dirigido a</label>
				<textarea 
					class="form-control{{ $errors->curso_form->has('dirigido_a') ? ' is-invalid' : ''}}" 
					name="dirigido_a"
					rows="4"
				>{{ old('dirigido_a') ?: $curso_->dirigido_a}}</textarea >
				@include('admin.partials.errors.form_alert', ['field' => 'dirigido_a'])
			</div>
		</div>

		<!-- campos objetivos-->
		<div class="col-sm-12 mt-4">
			<!-- incluimos la vista blade, y le pasamos los objetivos por parámetros -->
			@include('admin.partials.objetivo_form')
		</div>


	@if(!empty($btnTexto))
	<div class="col-sm-12 mt-4 text-center">
		<button type="submit" class="mx-2 btn btn-outline-primary">{{ __($btnTexto) }}</button>

		<a href="{{ url('/admin') }}" class="mx-2 btn btn-secondary">Cancelar</a>
	</div>
	@endif

</form>


@push('scripts')

<script type="text/javascript">
	
$( document ).ready(function() {	
	//Cargar nombre del fichero en el input file
		$('.custom-file-input').on('change', function() { 
			
		    var fileName = $(this).val().split('\\').pop(); 
		    //alert(fileName);
		    $(this).next('.custom-file-label').addClass("selected").html(fileName); 
		});
});

</script>

@endpush

resources/views/admin/partials/flash_messages.blade.php
@if( session("success") )
<div class="alert alert-success alert-block" role="alert">
    <button class="close" data-dismiss="alert"></button>
    {{ session("success") }}
</div>
@endif


@if( session("error") )
<div class="alert alert-danger alert-block" role="alert">
    <button class="close" data-dismiss="alert"></button>
    {{ session("error") }}
</div>
@endif

resources/views/admin/partials/objetivo_form.blade.php
<div class="card">
  <div class="card-header">
    {{ __('Objetivos') }}
  </div>
  <div class="card-body">
    
    <div class="card-text">
    	<!-- Vamos a permitir que como máximo se introduzcan 2 objetivos, el primero requeido y el segundo opcional-->
		<div class="form-group label-floating">
			<label for="objetivo1" class="control-label">Primer objetivo</label>
			<textarea
					class="form-control{{ $errors->curso_form->has('objetivos.0') ? ' is-invalid' : ''}}" 
					name="objetivos[]" 
					required
					rows="4"
			>{{ old('objetivos.0') ? old('objetivos.0') : ($curso_->objetivos_count>0 ? $curso_->objetivos[0]->objetivo : '') }}</textarea>
			@include('admin.partials.errors.form_alert', ['field' => 'objetivos.0'])

			<!-- para tener un control sobre el input primer objetivo-->
			@if($curso_->objetivos_count > 0)
				<input type="hidden" name="objetivo_id0" value="{{ $curso_->objetivos[0]->id }}">
			@endif
		</div>

		<div class="form-group label-floating">
			<label for="objetivo2" class="control-label">Segundo objetivo <small>(opcional)</small></label>
			<textarea
					class="form-control{{ $errors->curso_form->has('objetivos.1') ? ' is-invalid' : ''}}" 
					name="objetivos[]" 
					rows="2"
			>{{ old('objetivos.1') ? old('objetivos.1') : ($curso_->objetivos_count>1 ? $curso_->objetivos[1]->objetivo : '') }}</textarea>
			@include('admin.partials.errors.form_alert', ['field' => 'objetivos.1'])

			<!-- para tener un control sobre el input del segundo objetivo-->
			@if($curso_->objetivos_count > 1)
				<input type="hidden" name="objetivo_id1" value="{{ $curso_->objetivos[1]->id }}">
			@endif
		</div>
    </div>

  </div>
</div>

resources/views/admin/partials/select_form_temas.blade.php
              <div class="card mt-3"> 
                  <div class="card-body">
                      <div class="input-group">
                          <div class="input-group-prepend">
                              <label class="input-group-text">Tema</label>
                          </div>
                          <select class="custom-select" id="titulosTemas">
                            <option value="default">{{ __('-- Seleccione un tema --') }}</option>
                            @foreach($curso_->temas as $tema)
                                  <option id="tema{{$tema->id}}" value="{{ $tema->id }}">{{$tema->titulo}}</option>
                            @endforeach
                          </select>
                      </div>
                      
                  </div>
              </div>

resources/views/admin/partials/tabla_compras.blade.php
<!-- Tabla que se muestra en la vista admin.compras --> 
<div class="table-responsive-md">
	<table class="table mt-2">
	  	<thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Titulo</th>
		      <th scope="col" >Precio</th>
		      <th scope="col" >Desc</th>
		      <th scope="col" >Total €/curso</th>
		      <th scope="col" >Alumnos</th>
		      <th scope="col" >Total</th>
		      
		   </tr>
		</thead>
		<tbody>
		  	@php $ingresos = 0 @endphp
		    @foreach($compras as $detalle)
			    <tr>	
			      <th class="text-center" scope="row">{{ $detalle -> curso_id }}</th>
			      <td>{{ $detalle -> curso->titulo}}</td>
			      <td>{{ $detalle -> precio}} €</td>
			      <td>{{ $detalle -> descuento}}%</td>
			      <td>{{ $detalle -> getTotal() }} €</td>
			      <td>{{ $detalle->curso->users_count }}</td>
			      <td>{{ $detalle -> getTotal()* $detalle->curso->users_count}} €</td>
			    </tr>
			    @php 
			    	$total = $detalle -> getTotal()* $detalle->curso->users_count;
			    	$ingresos = $ingresos + $total;
			    @endphp
		    @endforeach
		    	<tr class="border-bottom-1">
		    		<td colspan="6" class="text-right"><h4>Ingresos total:</h4></td>
		    		<td><h5>{{ $ingresos }} €</h5></td>
		    	</tr>
		</tbody>
	</table>
	<div class="mt-2 d-flex justify-content-lg-center">	{{ $compras -> links () }} </div>
</div>

resources/views/admin/partials/tabla_cursos.blade.php
<!-- tabla que lista todos los cursos -->
<div class="table-responsive">
<table class="table mt-2">
  	<thead>
	    <tr>
	      <th class="text-center" scope="col">#</th>
	      <th scope="col">Titulo</th>
	      <th class="text-right" scope="col" >Precio</th>
	      <th class="text-right" scope="col" >Estado</th>
	      <th class="text-right" scope="col" >Opciones</th>
	    </tr>
		</thead>
  	<tbody>
    @foreach($cursos as $curso)
	    <tr>	
	      <th class="text-center" scope="row">{{ $curso -> id }}</th>
	      <td>{{ $curso -> titulo}}</td>
	      <td class="text-right">{{ $curso -> precio}} €</td>
	      <td class="text-right">
	      		@switch($curso -> estado)
				    @case(1)
				        {{ __('PENDIENTE') }}
				        @break

				    @case(2)
				        {{ __('PUBLICADO') }}
				        @break

				    @case(3)
				        {{ __('ELIMINADO') }}
				@endswitch
		 </td>
	      <td class="td-actions text-right">					
			<div class="d-inline-flex">
				<a href="{{ url('/admin/cursos/'. $curso -> slug) }}" rel="tooltip" title="Ver curso" class="btn btn-info btn-xs mr-1"><i class="fa fa-info-circle"></i></a href="">
	      		<a href="{{ url('/admin/cursos/'. $curso -> slug .'/editar') }}" rel="tooltip" title="Editar curso" class="btn btn-success btn-xs mr-1"><i class="fa fa-edit"></i></a>
	      	<form method="post" action="{{ url('/admin/cursos/'. $curso -> id) }}">{{ csrf_field()}}
	 			{{ method_field('DELETE')}}
	 			<button type="submit" rel="tooltip" title="Eliminar curso" class="btn btn-danger btn-xs mr-1"><i class="fa fa-times"></i></button>
	 		</form>
			</div>
	      </td>
	    </tr>
    @endforeach
  </tbody>
</table>
</div>

resources/views/admin/partials/tabla_temas.blade.php
<div class="table-responsive">
	<table id="tabla_temas" class="table mt-2 table-hover">
  	<thead>
	    <tr>
	    	<th class="text-center" scope="col"></th>
	      <th class="text-center" scope="col">{{ __('Nº') }}</th>
	      <th class="text-left" scope="col">{{ __('Titulo') }}</th>
	      <th class="text-right" scope="col" >{{ __('Opciones') }}</th>
	    </tr>
		</thead>
  <tbody>
    @foreach($curso_->temas as $tema)
	    <tr>	
	      <td class="text-center">
	      	<div class="d-inline-flex text-dark">
	      		<button type="button" class="up btn btn-outline-secondary mr-1"><i class="fa fa-angle-up" aria-hidden="true"></i></button>
	      		<button type="button" class="down btn btn-outline-secondary"><i class="fa fa-angle-down" aria-hidden="true"></i></button>
	      	</div>    	
		  </td>
		  <td class="posicion" data-tema="{{ $tema->id }}" scope="row"><strong>{{ $tema->posicion }}</strong></td>
	      <td class="text-left active">{{ $tema -> titulo}}</td>
	      <td class="td-actions text-right">					
	 			<div class="d-inline-flex">
	 				<!--  to add a modal and a tooltip without adding javascript or altering the tooltip function, you could also simply wrap an element around it: Then it add an span-->
		      		<span data-toggle="modal" 
		      				data-id="{{$tema->id}}"
		      				data-title="{{$tema->titulo}}" 
		      				data-descripcion="{{$tema->descripcion}}"
		      				data-target="#editTema" 
		      				id="editTema">
		      			<a href="#" 
		      				data-toggle="tooltip"
		      				data-placement="bottom" 
		      				title="Editar tema" 
		      				class="btn btn-info btn-xs mr-1"
		      			><i class="fa fa-edit"></i></a>
		      		</span><!-- ./ button to edit Tema -->
		      		<form method="post" action="{{ url('/admin/cursos/temas/'. $tema -> id) }}">{{ csrf_field()}}
		 				{{ method_field('DELETE')}}
		 				<button type="submit" data-toggle="tooltip" data-placement="bottom" title="Eliminar tema" class="btn btn-danger btn-xs  mr-1"><i class="fa fa-trash-o" aria-hidden="true"></i></button><!-- ./ button to delete Tema -->
		 			</form>
	 				 <button data-toggle="tooltip" title="Ver recursos" data-placement="bottom" class="btn btn-outline-info btn-xs mr-1" onclick="showRecursos({{ $tema->id }})"><i class="fa fa-paperclip" aria-hidden="true"></i>
	 				 </button><!-- ./ button to show recursos -->
	 			</div>
	      </td>
	    </tr>
    @endforeach
    <!-- Modal edit Tema -->
@include('admin.partials.modal.edit_tema')
  </tbody>
</table>

</div>


@push('scripts')
	<script>
			function showRecursos(id) {
					var p ="#titulosTemas option[value='"+id+"']";
					$(p).prop('selected', true);
					$("#titulosTemas").trigger('change');
			}

		$(document).ready(function(){

		    $('#editTema').on('show.bs.modal', function (e) {

			  	var modalButton = $(e.relatedTarget); // span that triggered the modal
			  	var titulo = modalButton.data('title'); //Extract info from data-* attributes
			  	var descripcion = modalButton.data('descripcion');
			  	var id = modalButton.data('id');

			  	var modal = $(this);
			  	modal.find('.modal-body #tema_id').val(id);
			  	modal.find('.modal-body #title').val(titulo);
			  	modal.find('.modal-body #descripcion').val(descripcion);

			});

		    
		});
</script>
@endpush